/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as VendorDashboardRouteImport } from './routes/vendor-dashboard'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PressRouteImport } from './routes/press'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MealsRouteImport } from './routes/meals'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsVendorIdRouteImport } from './routes/vendors.$vendorId'
import { Route as OrderConfirmationOrderIdRouteImport } from './routes/order-confirmation.$orderId'
import { Route as BlogVendorSpotlightMamaTRouteImport } from './routes/blog.vendor-spotlight-mama-t'
import { Route as Blog5TipsPerfectJollofRouteImport } from './routes/blog.5-tips-perfect-jollof'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor-dashboard',
  path: '/vendor-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsRoute = MealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsVendorIdRoute = VendorsVendorIdRouteImport.update({
  id: '/$vendorId',
  path: '/$vendorId',
  getParentRoute: () => VendorsRoute,
} as any)
const OrderConfirmationOrderIdRoute =
  OrderConfirmationOrderIdRouteImport.update({
    id: '/order-confirmation/$orderId',
    path: '/order-confirmation/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogVendorSpotlightMamaTRoute =
  BlogVendorSpotlightMamaTRouteImport.update({
    id: '/vendor-spotlight-mama-t',
    path: '/vendor-spotlight-mama-t',
    getParentRoute: () => BlogRoute,
  } as any)
const Blog5TipsPerfectJollofRoute = Blog5TipsPerfectJollofRouteImport.update({
  id: '/5-tips-perfect-jollof',
  path: '/5-tips-perfect-jollof',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/maintenance': typeof MaintenanceRoute
  '/meals': typeof MealsRoute
  '/notifications': typeof NotificationsRoute
  '/press': typeof PressRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/vendor-dashboard': typeof VendorDashboardRoute
  '/vendors': typeof VendorsRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/blog/5-tips-perfect-jollof': typeof Blog5TipsPerfectJollofRoute
  '/blog/vendor-spotlight-mama-t': typeof BlogVendorSpotlightMamaTRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/maintenance': typeof MaintenanceRoute
  '/meals': typeof MealsRoute
  '/notifications': typeof NotificationsRoute
  '/press': typeof PressRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/vendor-dashboard': typeof VendorDashboardRoute
  '/vendors': typeof VendorsRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/blog/5-tips-perfect-jollof': typeof Blog5TipsPerfectJollofRoute
  '/blog/vendor-spotlight-mama-t': typeof BlogVendorSpotlightMamaTRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/maintenance': typeof MaintenanceRoute
  '/meals': typeof MealsRoute
  '/notifications': typeof NotificationsRoute
  '/press': typeof PressRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/vendor-dashboard': typeof VendorDashboardRoute
  '/vendors': typeof VendorsRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/blog/5-tips-perfect-jollof': typeof Blog5TipsPerfectJollofRoute
  '/blog/vendor-spotlight-mama-t': typeof BlogVendorSpotlightMamaTRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/maintenance'
    | '/meals'
    | '/notifications'
    | '/press'
    | '/profile'
    | '/search'
    | '/signin'
    | '/signup'
    | '/vendor-dashboard'
    | '/vendors'
    | '/wishlist'
    | '/blog/5-tips-perfect-jollof'
    | '/blog/vendor-spotlight-mama-t'
    | '/order-confirmation/$orderId'
    | '/vendors/$vendorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/maintenance'
    | '/meals'
    | '/notifications'
    | '/press'
    | '/profile'
    | '/search'
    | '/signin'
    | '/signup'
    | '/vendor-dashboard'
    | '/vendors'
    | '/wishlist'
    | '/blog/5-tips-perfect-jollof'
    | '/blog/vendor-spotlight-mama-t'
    | '/order-confirmation/$orderId'
    | '/vendors/$vendorId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/maintenance'
    | '/meals'
    | '/notifications'
    | '/press'
    | '/profile'
    | '/search'
    | '/signin'
    | '/signup'
    | '/vendor-dashboard'
    | '/vendors'
    | '/wishlist'
    | '/blog/5-tips-perfect-jollof'
    | '/blog/vendor-spotlight-mama-t'
    | '/order-confirmation/$orderId'
    | '/vendors/$vendorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MealsRoute: typeof MealsRoute
  NotificationsRoute: typeof NotificationsRoute
  PressRoute: typeof PressRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorsRoute: typeof VendorsRouteWithChildren
  WishlistRoute: typeof WishlistRoute
  OrderConfirmationOrderIdRoute: typeof OrderConfirmationOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-dashboard': {
      id: '/vendor-dashboard'
      path: '/vendor-dashboard'
      fullPath: '/vendor-dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals': {
      id: '/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$vendorId': {
      id: '/vendors/$vendorId'
      path: '/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof VendorsVendorIdRouteImport
      parentRoute: typeof VendorsRoute
    }
    '/order-confirmation/$orderId': {
      id: '/order-confirmation/$orderId'
      path: '/order-confirmation/$orderId'
      fullPath: '/order-confirmation/$orderId'
      preLoaderRoute: typeof OrderConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/vendor-spotlight-mama-t': {
      id: '/blog/vendor-spotlight-mama-t'
      path: '/vendor-spotlight-mama-t'
      fullPath: '/blog/vendor-spotlight-mama-t'
      preLoaderRoute: typeof BlogVendorSpotlightMamaTRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/5-tips-perfect-jollof': {
      id: '/blog/5-tips-perfect-jollof'
      path: '/5-tips-perfect-jollof'
      fullPath: '/blog/5-tips-perfect-jollof'
      preLoaderRoute: typeof Blog5TipsPerfectJollofRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  Blog5TipsPerfectJollofRoute: typeof Blog5TipsPerfectJollofRoute
  BlogVendorSpotlightMamaTRoute: typeof BlogVendorSpotlightMamaTRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  Blog5TipsPerfectJollofRoute: Blog5TipsPerfectJollofRoute,
  BlogVendorSpotlightMamaTRoute: BlogVendorSpotlightMamaTRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface VendorsRouteChildren {
  VendorsVendorIdRoute: typeof VendorsVendorIdRoute
}

const VendorsRouteChildren: VendorsRouteChildren = {
  VendorsVendorIdRoute: VendorsVendorIdRoute,
}

const VendorsRouteWithChildren =
  VendorsRoute._addFileChildren(VendorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  MaintenanceRoute: MaintenanceRoute,
  MealsRoute: MealsRoute,
  NotificationsRoute: NotificationsRoute,
  PressRoute: PressRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorsRoute: VendorsRouteWithChildren,
  WishlistRoute: WishlistRoute,
  OrderConfirmationOrderIdRoute: OrderConfirmationOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
